sudo: required
services:
  - docker

before_install:
  - docker build -t eureka4eva/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run eureka4eva/react-test npm test -- --coverage

after_success:
  - docker build -t eureka4eva/multi-client ./client
  - docker build -t eureka4eva/multi-nginx ./nginx
  - docker build -t eureka4eva/multi-server ./server
  - docker build -t eureka4eva/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD"  |  docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
- docker push eureka4eva/multi-client
- docker push eureka4eva/multi-nginx
- docker push eureka4eva/multi-server
- docker push eureka4eva/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: "elasticbeanstalk-us-west-1-8889990"
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS-ACCESS_KEY 
  secret_access_key: 
    secure: $AWS_SECRET_KEY 
